import { ProjectType, LoaderType } from '@prisma/client';

export interface SeedVersion {
  version: string;
  changelog: string;
  weight: number;
}
export interface SeedProject {
  title: string;
  slug: string;
  type: ProjectType;
  description: string;
  features: string[];
  downloads: number;
  views: number;
  featured?: boolean;
  authorUsername: string;
  categorySlug: string;
  loaders: LoaderType[];
  gameVersions: string[];
  color: string;
  licenseShortId: string;
  sourceUrl?: boolean;
  wikiUrl?: boolean;
  discordUrl?: boolean;
  requires?: string[];
  versions?: SeedVersion[];
}

export const V = (...v: [string, string, number][]): SeedVersion[] =>
  v.map(([version, changelog, weight]) => ({ version, changelog, weight }));

export const USERS = [
  {
    username: 'admin',
    displayName: 'Platform Admin',
    email: 'admin@minecraftplatform.com',
    role: 'OWNER',
    bio: 'Official administrator account for the platform.',
  },
  {
    username: 'demo_admin',
    displayName: 'Demo Admin',
    email: 'demo@admin.com',
    role: 'ADMIN',
    bio: 'Demo admin account for testing.',
  },
  {
    username: 'demo_user',
    displayName: 'Demo User',
    email: 'demo@user.com',
    role: 'USER',
    bio: 'Demo user account for testing.',
  },
  {
    username: 'caffeinemc',
    displayName: 'CaffeineMC',
    email: 'team@caffeinemc.net',
    role: 'USER',
    bio: 'Performance optimization collective behind Sodium and Lithium.',
  },
  {
    username: 'mezz',
    displayName: 'mezz',
    email: 'mezz@jei.example',
    role: 'USER',
    bio: 'Author of JEI - Just Enough Items.',
  },
  {
    username: 'simibubi',
    displayName: 'Simibubi',
    email: 'simi@create.example',
    role: 'USER',
    bio: 'Creator of the Create mod and several addon mods.',
  },
  {
    username: 'irisshaders',
    displayName: 'Iris Shaders',
    email: 'team@irisshaders.dev',
    role: 'USER',
    bio: 'Shader loader for Minecraft compatible with OptiFine packs.',
  },
  {
    username: 'shedaniel',
    displayName: 'shedaniel',
    email: 'me@shedaniel.dev',
    role: 'USER',
    bio: 'Author of Cloth Config and Architectury.',
  },
  {
    username: 'Snownee',
    displayName: 'Snownee',
    email: 'snownee@example.com',
    role: 'USER',
    bio: 'Author of Jade and other QoL mods.',
  },
  {
    username: 'BlayTheNinth',
    displayName: 'BlayTheNinth',
    email: 'blay@example.com',
    role: 'USER',
    bio: 'Maker of Waystones and quality-of-life mods.',
  },
  {
    username: 'jaredlll08',
    displayName: 'jaredlll08',
    email: 'jared@example.com',
    role: 'MODERATOR',
    bio: 'Clumps, Controlling and more.',
  },
  {
    username: 'MehVahdJukaar',
    displayName: 'MehVahdJukaar',
    email: 'mehvahd@example.com',
    role: 'USER',
    bio: 'Author of Supplementaries and Moonlight Lib.',
  },
  {
    username: 'vsanthanam',
    displayName: 'Vswe',
    email: 'vswe@example.com',
    role: 'USER',
    bio: 'Worldgen enthusiast.',
  },
  {
    username: 'vectorwing',
    displayName: 'vectorwing',
    email: 'vector@example.com',
    role: 'USER',
    bio: 'Farmers Delight - cooking done right.',
  },
  {
    username: 'DrCyano',
    displayName: 'DrCyano',
    email: 'cyano@example.com',
    role: 'USER',
    bio: 'Worldgen modding since beta 1.7.',
  },
  {
    username: 'godshunter',
    displayName: 'Godshunter',
    email: 'gh@example.com',
    role: 'USER',
    bio: 'Shader pack author.',
  },
  {
    username: 'essentialsx',
    displayName: 'EssentialsX Team',
    email: 'team@essentialsx.net',
    role: 'USER',
    bio: 'The essential server plugin suite.',
  },
  {
    username: 'mcpackstudio',
    displayName: 'Pack Studio',
    email: 'studio@packs.example',
    role: 'USER',
    bio: 'Curated resource packs and datapacks.',
  },
];

export const CATEGORIES = [
  { name: 'Adventure', slug: 'adventure', icon: '🗺️', color: '#10b981', order: 1 },
  { name: 'Performance', slug: 'performance', icon: '⚡', color: '#f59e0b', order: 2 },
  { name: 'Technology', slug: 'technology', icon: '⚙️', color: '#3b82f6', order: 3 },
  { name: 'Utility', slug: 'utility', icon: '🔧', color: '#8b5cf6', order: 4 },
  { name: 'Magic', slug: 'magic', icon: '✨', color: '#ec4899', order: 5 },
  { name: 'Library', slug: 'library', icon: '📚', color: '#06b6d4', order: 6 },
  { name: 'World Gen', slug: 'worldgen', icon: '🌍', color: '#22c55e', order: 7 },
  { name: 'Food', slug: 'food', icon: '🍞', color: '#f97316', order: 8 },
  { name: 'Mobs', slug: 'mobs', icon: '🐺', color: '#ef4444', order: 9 },
  { name: 'Equipment', slug: 'equipment', icon: '⚔️', color: '#a3a3a3', order: 10 },
  { name: 'Decoration', slug: 'decoration', icon: '🏠', color: '#facc15', order: 11 },
];

export const MINECRAFT_VERSIONS = [
  ['1.21.4', '1.21.1', '1.21', '1.20.6', '1.20.4', '1.20.1', '1.19.4', '1.18.2', '1.16.5'].map(
    (v) => ({ version: v, type: 'release', stable: true }),
  ),
].flat();

const F = LoaderType.FABRIC,
  O = LoaderType.FORGE,
  N = LoaderType.NEOFORGE,
  Q = LoaderType.QUILT,
  B = LoaderType.BUKKIT,
  S = LoaderType.SPIGOT,
  P = LoaderType.PAPER;

export const PROJECTS: SeedProject[] = [
  // ── MODS ──
  {
    title: 'Sodium',
    slug: 'sodium',
    type: ProjectType.MOD,
    description:
      'A modern, high-performance rendering engine that dramatically improves frame rates.',
    features: [
      'Up to 5x higher frame rates than vanilla',
      'Reduced stutter and micro-freezes',
      'Advanced chunk-building multithreading',
      'Broad compatibility with performance mods',
    ],
    downloads: 12500000,
    views: 45000000,
    featured: true,
    authorUsername: 'caffeinemc',
    categorySlug: 'performance',
    loaders: [F],
    gameVersions: ['1.21.4', '1.21.1', '1.20.1'],
    color: '#10b981',
    licenseShortId: 'MIT',
    sourceUrl: true,
    versions: V(
      ['1.0.2', '- Fixed flickering shadows on AMD GPUs\n- Improved chunk upload throttling', 30],
      ['1.0.1', '- Added 1.21.4 support\n- Reduced VRAM usage by ~8%', 45],
      ['1.0.0', 'Initial 1.0 release with rewritten terrain pipeline.', 25],
    ),
  },
  {
    title: 'Lithium',
    slug: 'lithium',
    type: ProjectType.MOD,
    description:
      'General-purpose optimization mod improving game physics, block ticking and mob AI.',
    features: [
      'Optimized collision detection and pathfinding',
      'Faster mob AI with identical behavior',
      'Zero gameplay changes - pure speed',
    ],
    downloads: 8900000,
    views: 21000000,
    featured: true,
    authorUsername: 'caffeinemc',
    categorySlug: 'performance',
    loaders: [F, Q],
    gameVersions: ['1.21.4', '1.20.1'],
    color: '#84cc16',
    licenseShortId: 'LGPL-3.0',
  },
  {
    title: 'Just Enough Items (JEI)',
    slug: 'jei',
    type: ProjectType.MOD,
    description: 'View items and recipes in a clean, searchable interface.',
    features: [
      'Search every item and block instantly',
      'View crafting recipes and usage patterns',
      'Bookmark items with a keybind',
      'Supported by virtually every tech and magic mod',
    ],
    downloads: 15100000,
    views: 62000000,
    featured: true,
    authorUsername: 'mezz',
    categorySlug: 'utility',
    loaders: [F, O, N],
    gameVersions: ['1.21.4', '1.21.1', '1.20.1'],
    color: '#8b5cf6',
    licenseShortId: 'MIT',
    sourceUrl: true,
    wikiUrl: true,
    requires: ['fabric-api'],
    versions: V(
      ['19.21.0', '- Added 1.21.4 support\n- Bookmark overlay redesign', 35],
      ['19.20.0', '- Search history improvements\n- Recipe lookup performance pass', 40],
      ['19.18.0', '- Initial 1.21 port', 25],
    ),
  },
  {
    title: 'Create',
    slug: 'create',
    type: ProjectType.MOD,
    description: 'Aesthetic technology mod focused on building kinetic contraptions.',
    features: [
      'Rotational power instead of energy pipes',
      'Fully animated kinetic machines',
      'Trains, gantries and moving structures',
      'Extensive addon ecosystem',
    ],
    downloads: 8200000,
    views: 28000000,
    featured: true,
    authorUsername: 'simibubi',
    categorySlug: 'technology',
    loaders: [O, F, N],
    gameVersions: ['1.21.1', '1.20.1'],
    color: '#3b82f6',
    licenseShortId: 'MIT',
    sourceUrl: true,
    discordUrl: true,
    wikiUrl: true,
    versions: V(
      ['6.0.4', '- Train track rendering fixes\n- New cogwheel variants', 30],
      ['6.0.2', '- Added 1.21.1 support\n- Contraption stability improvements', 45],
      ['0.5.1', '- Legacy release for 1.20.1', 25],
    ),
  },
  {
    title: 'Iris Shaders',
    slug: 'iris',
    type: ProjectType.MOD,
    description: 'A modern shader pack loader for Minecraft.',
    features: [
      'Compatible with OptiFine shader packs',
      'Best-in-class Sodium integration',
      'Directional shading and colored shadows',
    ],
    downloads: 6800000,
    views: 22000000,
    authorUsername: 'irisshaders',
    categorySlug: 'decoration',
    loaders: [F],
    gameVersions: ['1.21.4', '1.21.1'],
    color: '#facc15',
    licenseShortId: 'LGPL-3.0',
  },
  {
    title: 'Fabric API',
    slug: 'fabric-api',
    type: ProjectType.MOD,
    description: 'Essential hooks and interoperability library for Fabric mods.',
    features: [
      'Events, registries and networking APIs',
      'Required by most Fabric mods',
      'Modular - disable unneeded parts',
    ],
    downloads: 18900000,
    views: 55000000,
    featured: true,
    authorUsername: 'shedaniel',
    categorySlug: 'library',
    loaders: [F],
    gameVersions: ['1.21.4', '1.21.1', '1.20.1'],
    color: '#d7a86e',
    licenseShortId: 'Apache-2.0',
  },
  {
    title: 'Cloth Config API',
    slug: 'cloth-config',
    type: ProjectType.MOD,
    description: 'Configuration screen API used by dozens of popular mods.',
    features: ['Declarative config screens', 'Cross-loader support', 'Auto-saving and validation'],
    downloads: 9400000,
    views: 30000000,
    authorUsername: 'shedaniel',
    categorySlug: 'library',
    loaders: [F, O],
    gameVersions: ['1.21.4', '1.20.1'],
    color: '#06b6d4',
    licenseShortId: 'LGPL-3.0',
  },
  {
    title: 'Architectury API',
    slug: 'architectury-api',
    type: ProjectType.MOD,
    description: 'An intermediary API easing multiplatform mod development.',
    features: [
      'Write once on Fabric and Forge',
      'Abstracted registries and events',
      'Huge cross-loader ecosystem',
    ],
    downloads: 12200000,
    views: 38000000,
    authorUsername: 'shedaniel',
    categorySlug: 'library',
    loaders: [F, O, N],
    gameVersions: ['1.21.4', '1.20.1'],
    color: '#c084fc',
    licenseShortId: 'Apache-2.0',
  },
  {
    title: 'Jade',
    slug: 'jade',
    type: ProjectType.MOD,
    description: 'Shows information about what you are looking at - blocks, entities, fluids.',
    features: [
      'WAILA-style HUD overlay',
      'Modded block and entity support',
      'Configurable display columns',
    ],
    downloads: 2620000,
    views: 9000000,
    authorUsername: 'Snownee',
    categorySlug: 'utility',
    loaders: [O, N, F],
    gameVersions: ['1.21.4', '1.20.1'],
    color: '#34d399',
    licenseShortId: 'MIT',
  },
  {
    title: 'Waystones',
    slug: 'waystones',
    type: ProjectType.MOD,
    description: 'Teleportation network blocks with a clean UI - travel without elytra.',
    features: [
      'Craftable, nameable waystones',
      'Dimension-restricted modes',
      'Map and JEI integrations',
    ],
    downloads: 7100000,
    views: 24000000,
    authorUsername: 'BlayTheNinth',
    categorySlug: 'utility',
    loaders: [O, N, F],
    gameVersions: ['1.21.1', '1.20.1'],
    color: '#60a5fa',
    licenseShortId: 'MIT',
  },
  {
    title: 'Clumps',
    slug: 'clumps',
    type: ProjectType.MOD,
    description: 'Clumps XP orbs together to reduce lag on servers and clients.',
    features: [
      'Automatic XP orb merging',
      'Noticeable tick-rate improvement',
      'Zero configuration needed',
    ],
    downloads: 3640000,
    views: 11000000,
    authorUsername: 'jaredlll08',
    categorySlug: 'performance',
    loaders: [N, O],
    gameVersions: ['1.21.4', '1.20.1'],
    color: '#a3e635',
    licenseShortId: 'MIT',
  },
  {
    title: 'Supplementaries',
    slug: 'supplementaries',
    type: ProjectType.MOD,
    description: 'Vanilla-plus decorations and gadgets: jars, cages, ropes, clocks and more.',
    features: [
      '200+ handcrafted vanilla-style blocks',
      'Datapack-driven customization',
      'Pairs perfectly with Moonlight Lib',
    ],
    downloads: 4200000,
    views: 15000000,
    authorUsername: 'MehVahdJukaar',
    categorySlug: 'decoration',
    loaders: [O, F],
    gameVersions: ['1.21.1', '1.20.1'],
    color: '#fb923c',
    licenseShortId: 'CC-BY-NC-4.0',
    discordUrl: true,
  },
  {
    title: 'Botania',
    slug: 'botania',
    type: ProjectType.MOD,
    description: 'A magic-themed tech mod built around flowers, mana and natural automation.',
    features: [
      'Mana-based power system',
      'Everything is physical in-world',
      'Beautiful cohesive art direction',
    ],
    downloads: 5400000,
    views: 19000000,
    authorUsername: 'vsanthanam',
    categorySlug: 'magic',
    loaders: [F, O],
    gameVersions: ['1.20.1'],
    color: '#f472b6',
    licenseShortId: 'MIT',
    sourceUrl: true,
  },
  {
    title: 'Applied Energistics 2',
    slug: 'applied-energistics-2',
    type: ProjectType.MOD,
    description: 'Digital storage networks, autocrafting and matter-energy conversion.',
    features: ['ME storage networks', 'Autocrafting CPU pipelines', 'Quantum bridge transport'],
    downloads: 6100000,
    views: 20000000,
    authorUsername: 'demo_admin',
    categorySlug: 'technology',
    loaders: [O, F],
    gameVersions: ['1.21.1', '1.20.1'],
    color: '#38bdf8',
    licenseShortId: 'MIT',
    sourceUrl: true,
    discordUrl: true,
  },
  {
    title: 'Twilight Forest',
    slug: 'twilight-forest',
    type: ProjectType.MOD,
    description: 'An expansive dimension packed with bosses, dungeons and progression.',
    features: [
      'Whole new overworld-like dimension',
      'Structured boss progression',
      'Unique biomes and hollow hills',
    ],
    downloads: 7800000,
    views: 26000000,
    authorUsername: 'demo_admin',
    categorySlug: 'adventure',
    loaders: [O, N],
    gameVersions: ['1.21.1', '1.20.1'],
    color: '#4ade80',
    licenseShortId: 'LGPL-3.0',
    sourceUrl: true,
  },
  {
    title: "Farmer's Delight",
    slug: 'farmers-delight',
    type: ProjectType.MOD,
    description: 'Cooking and farming done right - cutting boards, pots and hearty meals.',
    features: [
      'Dozens of new crops and recipes',
      'Cooking pot serving mechanics',
      'Villager farm integrations',
    ],
    downloads: 5900000,
    views: 17000000,
    authorUsername: 'vectorwing',
    categorySlug: 'food',
    loaders: [O, F, N],
    gameVersions: ['1.21.1', '1.20.1'],
    color: '#fbbf24',
    licenseShortId: 'MIT',
    sourceUrl: true,
  },
  {
    title: "Biomes O' Plenty",
    slug: 'biomes-o-plenty',
    type: ProjectType.MOD,
    description: 'Explore nearly 100 new biomes from lush wetlands to mystic groves.',
    features: ['~90 unique biomes', 'New wood types and plants', 'Configurable biome generation'],
    downloads: 9700000,
    views: 31000000,
    authorUsername: 'DrCyano',
    categorySlug: 'worldgen',
    loaders: [O, N],
    gameVersions: ['1.21.1', '1.20.1'],
    color: '#22c55e',
    licenseShortId: 'CC-BY-NC-SA-4.0',
    sourceUrl: true,
  },
  {
    title: 'Immersive Engineering',
    slug: 'immersive-engineering',
    type: ProjectType.MOD,
    description: 'Industrial tech with multiblock refineries, power lines and excavators.',
    features: [
      'Animated multiblock machines',
      'Wire-based power transmission',
      'Diesel generators and furnaces',
    ],
    downloads: 4800000,
    views: 16000000,
    authorUsername: 'demo_user',
    categorySlug: 'technology',
    loaders: [O],
    gameVersions: ['1.20.1'],
    color: '#94a3b8',
    licenseShortId: 'Custom',
    sourceUrl: true,
  },

  // ── SHADERS ──
  {
    title: 'Complementary Shaders',
    slug: 'complementary-shaders',
    type: ProjectType.SHADER,
    description: 'Feature-packed shader pack with Reimagined and Unbound editions.',
    features: [
      'Two visual styles in one pack',
      'Excellent performance tuning options',
      'Colored lighting and soft shadows',
    ],
    downloads: 3200000,
    views: 12000000,
    featured: true,
    authorUsername: 'godshunter',
    categorySlug: 'decoration',
    loaders: [F],
    gameVersions: ['1.21.4', '1.21.1', '1.20.1'],
    color: '#f59e0b',
    licenseShortId: 'ARR',
    requires: ['iris'],
    versions: V(
      ['5.4.1', '- Refined cloud lighting\n- Fixed rain puddles on glass', 30],
      ['5.3.0', '- New Reimagined emissives\n- Performance preset overhaul', 45],
      ['5.2.0', '- Initial 1.21 support', 25],
    ),
  },
  {
    title: 'BSL Shaders',
    slug: 'bsl-shaders',
    type: ProjectType.SHADER,
    description: 'Warm cinematic visuals balancing beauty and performance.',
    features: [
      'Signature warm color grading',
      'Customizable effects',
      'Great mid-range GPU performance',
    ],
    downloads: 4500000,
    views: 16000000,
    authorUsername: 'godshunter',
    categorySlug: 'decoration',
    loaders: [F],
    gameVersions: ['1.21.1', '1.20.1'],
    color: '#fda4af',
    licenseShortId: 'ARR',
    requires: ['iris'],
  },
  {
    title: 'Photon Shader',
    slug: 'photon-shader',
    type: ProjectType.SHADER,
    description: 'Crisp vibrant aesthetics designed for screenshot-quality gameplay.',
    features: ['PBR-style specular highlights', 'Hand-crafted water waves', 'Low ghosting TAA'],
    downloads: 1800000,
    views: 6000000,
    authorUsername: 'godshunter',
    categorySlug: 'decoration',
    loaders: [F],
    gameVersions: ['1.21.4', '1.21.1'],
    color: '#67e8f9',
    licenseShortId: 'CC-BY-4.0',
    requires: ['iris'],
  },

  // ── MODPACKS ──
  {
    title: 'Fabulously Optimized',
    slug: 'fabulously-optimized',
    type: ProjectType.MODPACK,
    description: 'Improves performance and graphics while keeping vanilla gameplay intact.',
    features: [
      '4x average FPS improvement',
      'Vanilla-parity gameplay',
      'Auto-updating via launcher',
    ],
    downloads: 5200000,
    views: 18000000,
    featured: true,
    authorUsername: 'demo_admin',
    categorySlug: 'performance',
    loaders: [F],
    gameVersions: ['1.21.4', '1.21.1'],
    color: '#f97316',
    licenseShortId: 'LGPL-3.0',
    discordUrl: true,
    versions: V(
      ['6.2.1', '- Sodium 1.0.2\n- Updated translations', 35],
      ['6.1.0', '- 1.21.4 day-one support\n- Modern fix alternatives', 45],
      ['5.4.0', '- Legacy 1.20.1 line', 20],
    ),
  },
  {
    title: 'Better MC - Forge Edition',
    slug: 'better-mc-forge',
    type: ProjectType.MODPACK,
    description: 'Enhance vanilla with new biomes, bosses, structures and QoL.',
    features: [
      '250+ curated mods',
      'New dimensions and endgame goals',
      'Server-ready configuration',
    ],
    downloads: 2900000,
    views: 12000000,
    featured: true,
    authorUsername: 'demo_admin',
    categorySlug: 'adventure',
    loaders: [O],
    gameVersions: ['1.20.1'],
    color: '#22c55e',
    licenseShortId: 'ARR',
    discordUrl: true,
  },
  {
    title: 'Prominence II RPG',
    slug: 'prominence-ii',
    type: ProjectType.MODPACK,
    description: 'RPG-focused modpack with classes, dungeons, quests and custom UI.',
    features: [
      'Skill trees and classes',
      'Hand-built quest book',
      'Hundreds of weapons and artifacts',
    ],
    downloads: 1400000,
    views: 7000000,
    authorUsername: 'demo_user',
    categorySlug: 'adventure',
    loaders: [F],
    gameVersions: ['1.20.1'],
    color: '#c084fc',
    licenseShortId: 'ARR',
  },
  {
    title: 'Create: Mechanical Mastery',
    slug: 'create-mechanical-mastery',
    type: ProjectType.MODPACK,
    description: 'Expert progression centered entirely around Create contraptions.',
    features: ['Gated expert progression', 'Quest lines per chapter', 'Rotational-power balance'],
    downloads: 850000,
    views: 3400000,
    authorUsername: 'simibubi',
    categorySlug: 'technology',
    loaders: [O],
    gameVersions: ['1.20.1'],
    color: '#3b82f6',
    licenseShortId: 'ARR',
  },

  // ── PLUGINS ──
  {
    title: 'EssentialsX',
    slug: 'essentialsx',
    type: ProjectType.PLUGIN,
    description: 'The essential suite for Bukkit servers - homes, warps, kits, moderation.',
    features: [
      '130+ commands out of the box',
      'Economy, chat and teleport modules',
      'Actively maintained',
    ],
    downloads: 2400000,
    views: 8000000,
    featured: true,
    authorUsername: 'essentialsx',
    categorySlug: 'utility',
    loaders: [B, S, P],
    gameVersions: ['1.21.4', '1.20.4'],
    color: '#fbbf24',
    licenseShortId: 'GPL-3.0',
    sourceUrl: true,
  },
  {
    title: 'WorldEdit',
    slug: 'worldedit',
    type: ProjectType.PLUGIN,
    description: 'In-game map editor for building and terraforming at scale.',
    features: ['Selection-based editing', 'Schematics save/load/share', 'Scripting support'],
    downloads: 3100000,
    views: 10000000,
    authorUsername: 'essentialsx',
    categorySlug: 'utility',
    loaders: [B, P, O],
    gameVersions: ['1.21.4', '1.20.1'],
    color: '#f59e0b',
    licenseShortId: 'LGPL-3.0',
    sourceUrl: true,
  },
  {
    title: 'LuckPerms',
    slug: 'luckperms',
    type: ProjectType.PLUGIN,
    description: 'A permissions plugin that is fast, reliable and easy to use.',
    features: ['Web permission editor', 'Contexts and prefixes', 'Every major platform supported'],
    downloads: 1900000,
    views: 6500000,
    authorUsername: 'essentialsx',
    categorySlug: 'utility',
    loaders: [B, P],
    gameVersions: ['1.21.4', '1.20.4'],
    color: '#818cf8',
    licenseShortId: 'MIT',
    sourceUrl: true,
  },
  {
    title: 'CoreProtect',
    slug: 'coreprotect',
    type: ProjectType.PLUGIN,
    description: 'Block logging and rollback - grief prevention tooling.',
    features: ['Fast database logging', 'One-command rollbacks', 'Container tracking'],
    downloads: 1200000,
    views: 4000000,
    authorUsername: 'demo_admin',
    categorySlug: 'utility',
    loaders: [P, S],
    gameVersions: ['1.21.1', '1.20.4'],
    color: '#94a3b8',
    licenseShortId: 'GPL-3.0',
  },

  // ── RESOURCE PACKS ──
  {
    title: 'Faithful 32x',
    slug: 'faithful-32x',
    type: ProjectType.RESOURCE_PACK,
    description: 'The classic double-resolution pack - vanilla look, twice the detail.',
    features: [
      'All vanilla textures at 32x',
      'Community-maintained completeness',
      'Consistent vanilla aesthetic',
    ],
    downloads: 2800000,
    views: 9000000,
    featured: true,
    authorUsername: 'mcpackstudio',
    categorySlug: 'decoration',
    loaders: [],
    gameVersions: ['1.21.4', '1.20.1'],
    color: '#f43f5e',
    licenseShortId: 'CC-BY-NC-SA-4.0',
  },
  {
    title: 'Bare Bones',
    slug: 'bare-bones',
    type: ProjectType.RESOURCE_PACK,
    description: 'Minimalist textures inspired by trailer art - flat colors, clean shapes.',
    features: ['Trailer-style palette', 'Perfect shader base', 'Lightweight for low-end PCs'],
    downloads: 950000,
    views: 3100000,
    authorUsername: 'mcpackstudio',
    categorySlug: 'decoration',
    loaders: [],
    gameVersions: ['1.21.4', '1.20.1'],
    color: '#fca5a5',
    licenseShortId: 'CC-BY-NC-4.0',
  },

  // ── DATA PACKS ──
  {
    title: 'Terralith',
    slug: 'terralith',
    type: ProjectType.DATA_PACK,
    description: 'Overworld overhaul with 100 handcrafted biomes using vanilla blocks only.',
    features: ['100+ custom biomes', 'Vanilla-friendly aesthetic', 'Compatible with worldgen mods'],
    downloads: 3300000,
    views: 11000000,
    featured: true,
    authorUsername: 'DrCyano',
    categorySlug: 'worldgen',
    loaders: [],
    gameVersions: ['1.21.4', '1.21.1', '1.20.1'],
    color: '#14b8a6',
    licenseShortId: 'CC-BY-NC-4.0',
    sourceUrl: true,
  },
  {
    title: 'Terra++',
    slug: 'terra-plus',
    type: ProjectType.DATA_PACK,
    description: 'Earth-inspired world generation using real elevation data.',
    features: ['Real-world terrain', 'Climate-based biomes', 'Region presets'],
    downloads: 480000,
    views: 1600000,
    authorUsername: 'vsanthanam',
    categorySlug: 'worldgen',
    loaders: [F],
    gameVersions: ['1.21.1'],
    color: '#2dd4bf',
    licenseShortId: 'MIT',
  },
  {
    title: 'Smithing Overhaul',
    slug: 'smithing-overhaul',
    type: ProjectType.DATA_PACK,
    description: 'Reworks the smithing table into deep weapon customization.',
    features: ['Tool part combinations', 'Material trait system', 'Survival-balanced'],
    downloads: 220000,
    views: 800000,
    authorUsername: 'demo_user',
    categorySlug: 'equipment',
    loaders: [],
    gameVersions: ['1.21.1', '1.20.1'],
    color: '#a78bfa',
    licenseShortId: 'MIT',
  },
];

export const COLLECTIONS = [
  {
    name: 'FPS Boost Pack',
    description: 'Squeeze every frame out of your game - the essential performance stack.',
    iconUrl: 'https://placehold.co/600x400/10b981/ffffff?text=FPS+BOOST',
    slugs: ['sodium', 'lithium', 'jei'],
  },
  {
    name: 'Tech & Automation',
    description: 'Build factories, contraptions and fully automated production lines.',
    iconUrl: 'https://placehold.co/600x400/3b82f6/ffffff?text=TECH+%26+AUTO',
    slugs: ['create', 'applied-energistics-2', 'immersive-engineering'],
  },
  {
    name: 'Shader Ready',
    description: 'Beautiful visuals start here - shader loaders and their best companions.',
    iconUrl: 'https://placehold.co/600x400/f59e0b/000000?text=SHADERS',
    slugs: ['iris', 'complementary-shaders', 'bsl-shaders', 'photon-shader'],
  },
  {
    name: 'Kitchen Sink Adventure',
    description: 'Exploration, bosses and progression - everything a survival player needs.',
    iconUrl: 'https://placehold.co/600x400/ef4444/ffffff?text=ADVENTURE',
    slugs: ['twilight-forest', 'waystones', 'farmers-delight'],
  },
  {
    name: 'Server Admin Toolkit',
    description: 'Run a smooth server: permissions, moderation, land claims and backups.',
    iconUrl: 'https://placehold.co/600x400/818cf8/ffffff?text=SERVER+ADMIN',
    slugs: ['essentialsx', 'luckperms', 'coreprotect', 'worldedit'],
  },
  {
    name: 'Cozy Vanilla+',
    description: 'Decorations, farming and small QoL that keep the vanilla feel.',
    iconUrl: 'https://placehold.co/600x400/facc15/000000?text=COZY+VANILLA',
    slugs: ['supplementaries', 'faithful-32x', 'bare-bones', 'terralith'],
  },
];
