# FreshClam Configuration
DatabaseDirectory /var/lib/clamav
UpdateLogFile /var/log/clamav/freshclam.log
LogTime yes
LogVerbose no
LogRotate yes
PidFile /var/run/clamav/freshclam.pid
DatabaseOwner clamav
Checks 24
DNSDatabaseInfo current.cvd.clamav.net
DatabaseMirror db.local.clamav.net
DatabaseMirror database.clamav.net
SafeBrowsing yes
Bytecode yes
NotifyClamd /etc/clamav/clamd.conf
